---
- name: Adding Docker repository
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    executable: /bin/bash

- name: Installing Docker
  shell: dnf install -y docker-ce docker-ce-cli containerd.io --nobest
  args:
    executable: /bin/bash

- name: Creating docker directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: Configuring Docker daemon file
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Creating docker service directory /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory