---
- name: Creating docker directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: Configuring Docker daemon file
  copy:
    src: conf.d/daemon.json
    dest: /etc/docker/daemon.json

- name: Creating docker service directory /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory