---
- name: Adding Docker repository
  shell: sudo dnf -y install dnf-plugins-core
  args:
    executable: /bin/bash

- name: Adding Docker repository
  shell: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    executable: /bin/bash

- name: Installing Docker
  shell: sudo dnf install docker-ce docker-ce-cli containerd.io -y
  args:
    executable: /bin/bash

- name: Creating docker directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: Configuring Docker daemon file
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

# - name: Creating docker service directory /etc/systemd/system/docker.service.d
#   file:
#     path: /etc/systemd/system/docker.service.d
#     state: directory

- name: Starting & enabling docker
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: docker