# - include: firewall.yaml
- include: packages.yaml
- include: docker.yaml

- name: Starting & enabling Docker
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: docker
  
- name: Starting & enabling kubelet
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: kubelet

- name: Stopping service firewalld
  systemd:
    name: firewalld
    state: stopped
    daemon_reexec: yes
    daemon_reload: yes

- name: Disabling Selinux
  lineinfile:
    path: /etc/sysconfig/selinux
    regex: SELINUX=enforcing
    line: SELINUX=disabled
    state: present

- name: Add br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Allowing iptables to see bridged traffic on ipv4
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Allowing iptables to see bridged traffic on ipv6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Turn off Swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/cl-swap'
    line: '#/dev/mapper/cl-swap'

- name: Download cni-plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
    dest: .

- name: mkdir /opt/cni/bin/
  file:
    path: /opt/cni/bin/
    state: directory

- name: Extract cni-plugins-amd64-v0.7.1.tgz into /opt/cni/bin/
  shell: tar -xvf cni-plugins-amd64-v0.7.1.tgz -C /opt/cni/bin/
  args:
    executable: /bin/bash

- name: Clean artifact cni-plugins
  file:
    state: absent
    path: cni-plugins-amd64-v0.7.1.tgz