---
# - name: Removing libnfsidmap
#   dnf:
#     name: 
#     - libnfsidmap
#     state: absent
#     autoremove: yes

- copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf

- shell: sudo modprobe overlay && sudo modprobe br_netfilter

- name: Adding Kubernetes repository
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

# - name: Enabling CRI-O
#   shell: sudo dnf module enable cri-o:1.14 -y

    
- name: Installing required packages
  dnf:
    name:
    - kubectl
    - kubeadm
    - kubelet
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - dnf-plugins-core
    - ipvsadm
    - python3
    update_cache: true
    state: latest

