---
# Setting ssh configuration
  - name: Setting ssh banner configuration
    template:
      src: ./templates/sshd-banner.j2
      dest: /etc/ssh/sshd-banner
  
  - name: Adding ssh banner location to /etc/ssh/sshd_config
    lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Banner /etc/ssh/sshd-banner'

  - name: Disbaling root login
    file:
      path: /etc/sshd/sshd_config.d/01-permitrootlogin.conf

  - name: Disbaling root login
    lineinfile:
        path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'
  
  - name: Disbaling root login
    file:
      path: /etc/sshd/sshd_config.d/01-passwordauthentication.conf

  - name: Restarting sshd
    shell: systemctl restart sshd
    args:
      executable: /bin/bash
