---
# Setting ssh configuration
  - name: Setting hostname of nodes
    shell: sudo hostnamectl set-hostname {{hostvars[groups['nodes'][groups['nodes'].index(inventory_hostname)]].inventory_hostname}}

  - name: Setting ssh banner configuration
    template:
      src: ./templates/sshd-banner.j2
      dest: /etc/ssh/sshd-banner
  
  - name: Adding ssh banner location to /etc/ssh/sshd_config
    lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Banner /etc/ssh/sshd-banner'

  - name: Disbaling root login
    file:
      path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
      state: touch

  - name: Disbaling root login
    lineinfile:
        path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
        line: 'PermitRootLogin no'
  
  - name: Disbaling password login
    file:
      path: /etc/ssh/sshd_config.d/01-passwordauthentication.conf
      state: touch

  # - name: Disbaling password login
  #   lineinfile:
  #       path: /etc/ssh/sshd_config.d/01-passwordauthentication.conf
  #       line: 'PasswordAuthentication no'

  # - name: Changing Ansible user to default
  #   delegate_to: localhost
  #   lineinfile:
  #     path: inventory.cfg
  #     regexp: '^ansible_user = root'
  #     line: 'ansible_user = default'

  - name: Restarting sshd
    shell: systemctl restart sshd
    args:
      executable: /bin/bash
