---
- name: Adding user default
  user:
    name: default
    group: wheel

- name: Creating .ssh directory
  file:
    path: /home/default/.ssh
    state: directory
    mode: 0700
    owner: default
    group: wheel
    recurse: true

- name: Copying root SSH public key to default user & fixing permissions for authorized keys
  shell: cp -rf ~/.ssh/authorized_keys /home/default/.ssh/authorized_keys && chmod 640 /home/default/.ssh/authorized_keys && chown -R default:wheel /home/default/.ssh
  args:
      executable: /bin/bash

- name: Adding Wheel to sudoers with nopasswd
  lineinfile:
    path: /etc/sudoers
    regexp: '^# %wheel        ALL=(ALL)       NOPASSWD: ALL'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'

# - name: Setting file permissions
#   shell: chown root:root /etc/anacrontab && chmod og-rwx /etc/anacrontab && chown root:root /etc/crontab && chmod og-rwx /etc/crontab && chown root:root /etc/cron.hourly && chmod og-rwx /etc/cron.hourly && chown root:root /etc/cron.daily && chmod og-rwx /etc/cron.daily && chown root:root /etc/cron.weekly && chmod og-rwx /etc/cron.weekly && chown root:root /etc/cron.monthly && chmod og-rwx /etc/cron.monthly && chown root:root /etc/cron.d && chmod og-rwx /etc/cron.d && chmod 644 /etc/passwd && chown root:root /etc/passwd && chmod 644 /etc/group && chown root:root /etc/group && chmod 600 /etc/shadow && chown root:root /etc/shadow && chmod 600 /etc/gshadow && chown root:root /etc/gshadow && chown root:root /var/spool/cron && chmod og-rwx /var/spool/cron
#   args:
#       executable: /bin/bash

- name: Creating vim run time directory /home/default/.vim_runtime/
  file:
    path: /home/default/.vim_runtime/
    state: directory

- name: Cloning amix vim git repo
  git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: /root/.vim_runtime
    clone: yes

- name: Installing custom vim
  shell: sh '/root/.vim_runtime/install_awesome_vimrc.sh'
  args:
    executable: /bin/bash
