---
- name: Adding user default
  user:
    name: default
    group: wheel

- name: Creating .ssh directory
  file:
    path: /home/default/.ssh
    state: directory
    mode: 0700
    owner: default
    group: wheel
    recurse: true

- name: Creating authorized_keys file
  file:
    path: /home/default/.ssh/authorized_keys
    state: touch
    
- name:
  lineinfile:
    path: /home/default/.ssh/authorized_keys
    line: "{{ ssh_auth_key }}"

# - name: Copying root SSH public key to default user & fixing permissions for authorized keys
#   shell: cp -rf ~/.ssh/authorized_keys /home/default/.ssh/authorized_keys && chmod 640 /home/default/.ssh/authorized_keys && chown -R default:wheel /home/default/.ssh
#   args:
#       executable: /bin/bash

- name: Adding Wheel to sudoers with nopasswd
  lineinfile:
    path: /etc/sudoers
    regexp: '^# %wheel        ALL=(ALL)       NOPASSWD: ALL'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'


