---
- name: Removing libnfsidmap
  dnf:
    name: 
    - libnfsidmap
    state: absent
    autoremove: yes

- name: Installing required packages
  dnf:
    name: 
    - nfs-utils
    update_cache: true
    state: latest